//! Managed state: the set of modules (name -> path) and allowed mesh IPs
//! this receiver exposes, persisted as JSON, with a generated `rsyncd.conf`
//! kept in lockstep on every mutation.
//!
//! `rsyncd.conf` itself is a derived artifact, never hand-edited -- `State`
//! in `state.json` is the single source of truth `module`/`allow`/`port`
//! subcommands read and write. rsync's daemon re-reads `rsyncd.conf` on
//! every new connection (documented rsync behavior), so a module/allow edit
//! here takes effect immediately with no daemon restart; only a port change
//! needs one -- currently only reachable via `install --port`, which
//! already restarts the service itself (see `service::install`).
//!
//! No `uid`/`gid` directives in the generated file: those are silently
//! ignored by rsync unless the daemon runs as root (it deliberately never
//! does here -- see main.rs), so omitting them avoids implying a privilege
//! this process does not have.

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Default port: derived from rsync's own standard port 873, shifted into
/// the non-privileged range (>1024) so this never needs root to bind it --
/// the whole point of running as a per-user service.
pub const DEFAULT_PORT: u16 = 8873;

#[derive(Serialize, Deserialize, Clone)]
pub struct Module {
    pub name: String,
    pub path: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct State {
    #[serde(default = "default_port")]
    pub port: u16,
    #[serde(default)]
    pub modules: Vec<Module>,
    /// Mesh IPs allowed to connect, shared across all modules (a global
    /// `hosts allow` line, not per-module -- v1 has one receiver, one
    /// allow-list; see DO-NOT-COMMIT/PLAN for the per-module rationale).
    #[serde(default)]
    pub allow: Vec<String>,
}

fn default_port() -> u16 {
    DEFAULT_PORT
}

impl Default for State {
    fn default() -> Self {
        State {
            port: DEFAULT_PORT,
            modules: Vec::new(),
            allow: Vec::new(),
        }
    }
}

fn data_dir() -> Result<PathBuf> {
    let dir = dirs::data_dir()
        .context("could not determine data directory")?
        .join("tetron-sync-receiver");
    fs::create_dir_all(&dir)?;
    Ok(dir)
}

fn state_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("state.json"))
}

pub fn rsyncd_conf_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("rsyncd.conf"))
}

pub fn pid_file_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("rsyncd.pid"))
}

pub fn log_file_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("rsyncd.log"))
}

pub fn load() -> Result<State> {
    let path = state_path()?;
    if !path.exists() {
        return Ok(State::default());
    }
    let raw = fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
    serde_json::from_str(&raw).with_context(|| format!("failed to parse {}", path.display()))
}

/// Persists `state.json` and regenerates `rsyncd.conf` together -- every
/// mutating subcommand goes through this so the two can never drift apart.
pub fn save(state: &State) -> Result<()> {
    let path = state_path()?;
    let raw = serde_json::to_string_pretty(state)?;
    fs::write(&path, raw).with_context(|| format!("failed to write {}", path.display()))?;
    write_rsyncd_conf(state)?;
    Ok(())
}

fn write_rsyncd_conf(state: &State) -> Result<()> {
    let path = rsyncd_conf_path()?;
    let mut out = String::new();
    out.push_str("# Generated by tetron-sync-receiver -- do not hand-edit, run\n");
    out.push_str("# `tetron-sync-receiver module`/`allow` subcommands instead.\n");
    out.push_str(&format!("pid file = {}\n", pid_file_path()?.display()));
    out.push_str(&format!("log file = {}\n", log_file_path()?.display()));
    out.push_str("use chroot = false\n");
    if state.allow.is_empty() {
        // No allow-list configured yet: deny everything rather than
        // defaulting open. An operator must explicitly add at least one
        // mesh IP before this receiver accepts any connection.
        out.push_str("hosts deny = *\n");
    } else {
        out.push_str(&format!("hosts allow = {}\n", state.allow.join(", ")));
        out.push_str("hosts deny = *\n");
    }
    out.push('\n');
    for module in &state.modules {
        out.push_str(&format!("[{}]\n", module.name));
        out.push_str(&format!("    path = {}\n", module.path));
        out.push_str("    read only = false\n\n");
    }
    fs::write(&path, out).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}
